AllCops:
    NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Layout/LineLength:
  Enabled: false