version: '3'
services:
  webhook-king:
    ports: 
      - 3000:3000
    image: webhook-king:latest
    container_name: webhook-king
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      - ENV=production
      - RAILS_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - ./log:/webhook-king/log
      - ./public:/webhook-king/public # nginx 可以处理内容
      - ./public:/webhook-king/public/ # nginx 可以处理内容
      - ./public/assets:/webhook-king/public/assets # nginx 可以处理内容
      - ./public/packs:/webhook-king/public/packs # nginx 可以处理内容
      - ./tmp/pids:/webhook-king/tmp/pids
  db:
    image: postgres:10
    volumes:
      - "./datadir/postgresql:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=webhook-king
  redis:
    image: redis:4
    volumes:
      - './datadir/redis:/data'
