version: '3'
services:
  webhooking:
    ports: 
      - 3000:3000
    # image: webhooking:latest
    build: .
    container_name: webhooking
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rails s -b 0.0.0.0 -p 3000"
    environment:
      - ENV=production
      - RAILS_ENV=production
      - PG_HOST=db
      - PG_POOL=30
      - PG_USER=postgres
      - POSTGRES_PASSWORD=webhooking
      - POSTGRES_DB=webhooking_production
      - PG_PORT=5433
      - REDIS_URL=redis://redis:6379/10
      - SENTRY_DSN=
      - WEBSITE_URL=http://localhost:3005
    depends_on:
      - redis
      - db
    volumes:
      - ./log:/webhooking/log
      - ./public:/webhooking/public # nginx 可以处理内容
      - ./public:/webhooking/public/ # nginx 可以处理内容
      - ./public/assets:/webhooking/public/assets # nginx 可以处理内容
      - ./public/packs:/webhooking/public/packs # nginx 可以处理内容
      - ./tmp/pids:/webhooking/tmp/pids
  db:
    image: postgres:14
    volumes:
      - "./datadir/postgresql:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=webhooking
  redis:
    image: redis:6
    volumes:
      - './datadir/redis:/data'
