PG_HOST: ''
PG_POOL: ''
PG_USER: ''
PG_PASSWORD: ''
PG_NAME: ''
PG_PORT: ''

CACHE_REDIS_HOST: redis
CACHE_REDIS_PORT: "6379"
CACHE_REDIS_PASSWORD: 
CACHE_REDIS_DB: 1
JOB_REDIS_URL: "redis://redis:6379/3"