default: &default
  adapter: postgresql
  host: <%= ENV["DB_HOST"] || '127.0.0.1' %>
  port: <%= ENV["PG_PORT"] || '5432' %>
development:
  <<: *default
  pool: 5
  database: webhook_king_development

test:
  <<: *default
  database: webhook_king_test

production:
  adapter: postgresql
  host: <%= ENV["PG_HOST"]  %>
  pool: <%= ENV["PG_POOL"] || 50 %>
  username:  <%= ENV['PG_USER'] || 'webhook_king_postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'webhook_king==' %>
  database: <%= ENV["PG_NAME"] || 'webhook_king_production' %>
  port: <%= ENV["PG_PORT"] || '3433' %>