default: &default
  adapter: postgresql
  host: <%= ENV["DB_HOST"] || '127.0.0.1' %> 
 
development:
  <<: *default
  pool: 20
  database: rails6_development

test:
  <<: *default
  database: rails6_test

production:
  adapter: postgresql
  host: <%= ENV["PG_HOST"]  %>
  pool: <%= ENV["PG_POOL"] || 50 %>
  username:  <%= ENV['PG_USER'] || 'rails6_postgres' %>
  password: <%= ENV['PG_PASSWORD'] || 'rails6==' %>
  database: <%= ENV["PG_NAME"] || 'rails6_production' %>
  port: <%= ENV["PG_PORT"] || '3433' %>